package frames;

import frames.products.PanelProducts;
import java.awt.*;
import java.awt.event.*;
import java.net.MalformedURLException;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PanelMenu extends javax.swing.JFrame {   
    String actualDate;
    public String filePath;   
    private int posX, posY;
    
    public PanelMenu() {                                                                  
        //setUndecorated(true);  
        super("A&V Dinning Room");
        initComponents();
        setLocationRelativeTo(null);                   
        
        LocalDate date = LocalDate.now();  
        
        actualDate = date.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH)+" "+date.getMonth().name()+" "+date.getDayOfMonth()+" "+date.getYear();
        jlDate.setText( actualDate);
        
        Color colorMainButton = new Color(38, 69, 159); 
        jbConsumption.setBackground(colorMainButton);
        jbBeneficiaries.setBackground(colorMainButton);
        jbLunchOfTheDay.setBackground(colorMainButton);
        
        PanelWelcome pWelcome = new PanelWelcome(this);
        pWelcome.setSize(1057, 660);
        pWelcome.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(pWelcome, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();      
        
        jlTitleContent.setText("Bienvenido");
        
        //Para poder arrastrar la ventana sin necesidad de decoracion
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                // Calcula la nueva posición de la ventana
                int newX = evt.getXOnScreen() - posX;
                int newY = evt.getYOnScreen() - posY;

                // Establece la nueva posición
                setLocation(newX, newY);
            }
        });
    }
    
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }    
    
    public JButton getButtonAddUser() {
        return jbConsumption;
    }
    
    public JButton getButtonDeleteUser() {
        return jbBeneficiaries;
    }
    
    public JButton getButtonListUsers() {
        return jbLunchOfTheDay;
    }
    
    public void setPanelContent(JPanel val) {
        jpContent.removeAll();
        jpContent.add(val, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint(); 
    }
    
    public JPanel getPanelContent() {
        return jpContent;
    }
    
    public JLabel getjlTitleContent() {
        return jlTitleContent;
    }

    public void setjlTitleContent(String jlTitle) {
        this.jlTitleContent.setText(jlTitle);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jlLogotipe = new javax.swing.JLabel();
        jbWelcome = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jpTitleContent = new javax.swing.JPanel();
        jlTitleContent = new javax.swing.JLabel();
        jlDate = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();
        jpLeftPanel = new javax.swing.JPanel();
        jbConsumption = new javax.swing.JButton();
        jbBeneficiaries = new javax.swing.JButton();
        jbLunchOfTheDay = new javax.swing.JButton();
        jbUsers = new javax.swing.JButton();
        jbProducts = new javax.swing.JButton();
        jbDownload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1147483647, 1147483647));

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel1.setBackground(new java.awt.Color(102, 151, 255));

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-user-25.png")); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlLogotipe.setBackground(new java.awt.Color(102, 102, 255));
        jlLogotipe.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jlLogotipe.setForeground(new java.awt.Color(255, 255, 255));
        jlLogotipe.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-restaurant-25.png")); // NOI18N
        jlLogotipe.setText("Amor y Vida");
        jlLogotipe.setToolTipText("");
        jlLogotipe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlLogotipe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jbWelcome.setBackground(new java.awt.Color(102, 151, 255));
        jbWelcome.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 13)); // NOI18N
        jbWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jbWelcome.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-home-20.png")); // NOI18N
        jbWelcome.setText("Principal");
        jbWelcome.setBorder(null);
        jbWelcome.setBorderPainted(false);
        jbWelcome.setContentAreaFilled(false);
        jbWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbWelcome.setFocusPainted(false);
        jbWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbWelcomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jlLogotipe, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogotipe)
                    .addComponent(jbWelcome)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                contentComponentAdded(evt);
            }
        });

        jpTitleContent.setBackground(new java.awt.Color(255, 255, 255));
        jpTitleContent.setForeground(new java.awt.Color(51, 51, 51));

        jlTitleContent.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlTitleContent.setForeground(new java.awt.Color(51, 51, 51));
        jlTitleContent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlTitleContent.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jlDate.setBackground(new java.awt.Color(38, 69, 159));
        jlDate.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jlDate.setForeground(new java.awt.Color(51, 51, 51));
        jlDate.setText("Date");
        jlDate.setToolTipText("");
        jlDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlDate.setFocusable(false);
        jlDate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpTitleContentLayout = new javax.swing.GroupLayout(jpTitleContent);
        jpTitleContent.setLayout(jpTitleContentLayout);
        jpTitleContentLayout.setHorizontalGroup(
            jpTitleContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleContentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlTitleContent, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jpTitleContentLayout.setVerticalGroup(
            jpTitleContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleContentLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jpTitleContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitleContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jpContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTitleContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jpTitleContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpLeftPanel.setBackground(new java.awt.Color(241, 241, 241));
        jpLeftPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbConsumption.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbConsumption.setForeground(new java.awt.Color(102, 102, 102));
        jbConsumption.setText("  Registrar consumo");
        jbConsumption.setBorder(null);
        jbConsumption.setBorderPainted(false);
        jbConsumption.setContentAreaFilled(false);
        jbConsumption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConsumption.setFocusPainted(false);
        jbConsumption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsumptionActionPerformed(evt);
            }
        });

        jbBeneficiaries.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbBeneficiaries.setForeground(new java.awt.Color(102, 102, 102));
        jbBeneficiaries.setText("  Beneficiarios");
        jbBeneficiaries.setBorder(null);
        jbBeneficiaries.setBorderPainted(false);
        jbBeneficiaries.setContentAreaFilled(false);
        jbBeneficiaries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBeneficiaries.setFocusPainted(false);
        jbBeneficiaries.setHideActionText(true);
        jbBeneficiaries.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbBeneficiaries.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jbBeneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBeneficiariesActionPerformed(evt);
            }
        });

        jbLunchOfTheDay.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbLunchOfTheDay.setForeground(new java.awt.Color(102, 102, 102));
        jbLunchOfTheDay.setText("  Almuerzo del día");
        jbLunchOfTheDay.setBorder(null);
        jbLunchOfTheDay.setBorderPainted(false);
        jbLunchOfTheDay.setContentAreaFilled(false);
        jbLunchOfTheDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLunchOfTheDay.setFocusPainted(false);
        jbLunchOfTheDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLunchOfTheDayActionPerformed(evt);
            }
        });

        jbUsers.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbUsers.setForeground(new java.awt.Color(102, 102, 102));
        jbUsers.setText("  Usuarios");
        jbUsers.setBorder(null);
        jbUsers.setBorderPainted(false);
        jbUsers.setContentAreaFilled(false);
        jbUsers.setFocusPainted(false);
        jbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsersActionPerformed(evt);
            }
        });

        jbProducts.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbProducts.setForeground(new java.awt.Color(102, 102, 102));
        jbProducts.setText("  Productos");
        jbProducts.setBorder(null);
        jbProducts.setBorderPainted(false);
        jbProducts.setContentAreaFilled(false);
        jbProducts.setFocusPainted(false);
        jbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductsActionPerformed(evt);
            }
        });

        jbDownload.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        jbDownload.setForeground(new java.awt.Color(102, 102, 102));
        jbDownload.setText("  Inventario");
        jbDownload.setBorder(null);
        jbDownload.setBorderPainted(false);
        jbDownload.setContentAreaFilled(false);
        jbDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDownload.setFocusPainted(false);
        jbDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDownloadActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-waiter-30.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-users-30.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-myspace-3-30.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-products-30.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-table-30.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-tableware-30.png")); // NOI18N

        javax.swing.GroupLayout jpLeftPanelLayout = new javax.swing.GroupLayout(jpLeftPanel);
        jpLeftPanel.setLayout(jpLeftPanelLayout);
        jpLeftPanelLayout.setHorizontalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbLunchOfTheDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbConsumption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbBeneficiaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(109, 109, 109))))
        );
        jpLeftPanelLayout.setVerticalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLunchOfTheDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBeneficiaries, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsumptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsumptionActionPerformed
        PanelConsumption pConsumption = new PanelConsumption(this);
        pConsumption.setSize(1097, 685);
        pConsumption.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(pConsumption, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint(); 
        
        jlTitleContent.setText("Registrar consumo");
    }//GEN-LAST:event_jbConsumptionActionPerformed

    public void botonResaltado() {
    
        // Agregar un MouseListener al botón
        jbConsumption.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Cambiar el color de fondo cuando el mouse entra
                jbConsumption.setBackground(Color.YELLOW);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Restaurar el color de fondo cuando el mouse sale
                jbConsumption.setBackground(UIManager.getColor("Button.background"));
            }
        });       
    };
    
    private void jbBeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBeneficiariesActionPerformed
               
        ListBeneficiaries listBeneficiaries = new ListBeneficiaries(this);
        listBeneficiaries.setSize(1097, 685);
        listBeneficiaries.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(listBeneficiaries, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();    
        
        jlTitleContent.setText("Lista de beneficiarios");
    }//GEN-LAST:event_jbBeneficiariesActionPerformed

    private void jbLunchOfTheDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLunchOfTheDayActionPerformed
        PanelLunchOfTheDay lunchOfTheDay = new PanelLunchOfTheDay(this);
        lunchOfTheDay.setSize(1097, 685);
        lunchOfTheDay.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(lunchOfTheDay, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();      
        
        jlTitleContent.setText("Almuerzo del día");
    }//GEN-LAST:event_jbLunchOfTheDayActionPerformed

    private void jbDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDownloadActionPerformed
                    
        PanelInventory inventory = new PanelInventory(this);
        inventory.setSize(1097, 685);
        inventory.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(inventory, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();  
        
        jlTitleContent.setText("Inventario");
    }//GEN-LAST:event_jbDownloadActionPerformed

    private void contentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_contentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_contentComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres cerrar sesión?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Cierra la ventana
            dispose();
            // Termina la aplicación
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsersActionPerformed
        // TODO add your handling code here:
        ListUsers listUsers = new ListUsers(this);
        listUsers.setSize(1097, 685);
        listUsers.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(listUsers, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint(); 
        
        jlTitleContent.setText("Listado de usuarios");
    }//GEN-LAST:event_jbUsersActionPerformed

    private void jbWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbWelcomeActionPerformed
        // TODO add your handling code here:
        PanelWelcome pWelcome = new PanelWelcome(this);
        pWelcome.setSize(1097, 685);
        pWelcome.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(pWelcome, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();  
        
        jlTitleContent.setText("Bienvenido");
    }//GEN-LAST:event_jbWelcomeActionPerformed

    private void jbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductsActionPerformed
        PanelProducts pProducts = new PanelProducts(this);
        pProducts.setSize(1097, 685);
        pProducts.setLocation(0, 0);                  
        
        jpContent.removeAll();
        jpContent.add(pProducts, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();  
        
        jlTitleContent.setText("Listado de productos");
    }//GEN-LAST:event_jbProductsActionPerformed

    public void setIconFromFile(String filePath) throws MalformedURLException {
        // Crea un ImageIcon a partir de la ruta del archivo
        ImageIcon icon = new ImageIcon(new ImageIcon(filePath).getImage());
        // Establece el icono en el JLabel
        //getIconFile().setIcon(icon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PanelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBeneficiaries;
    private javax.swing.JButton jbConsumption;
    private javax.swing.JButton jbDownload;
    private javax.swing.JButton jbLunchOfTheDay;
    private javax.swing.JButton jbProducts;
    private javax.swing.JButton jbUsers;
    private javax.swing.JButton jbWelcome;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlLogotipe;
    private javax.swing.JLabel jlTitleContent;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpLeftPanel;
    private javax.swing.JPanel jpTitleContent;
    // End of variables declaration//GEN-END:variables
}
