package frames;

import java.awt.*;
import java.awt.event.*;
import java.net.MalformedURLException;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PanelMenu extends javax.swing.JFrame {   
    String actualDate;
    public String filePath;   
    private int posX, posY;
    
    public PanelMenu() {                                                                  
        setUndecorated(true);  
        initComponents();
        setLocationRelativeTo(null);                   
        
        LocalDate date = LocalDate.now();  
        
        actualDate = date.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH)+" "+date.getMonth().name()+" "+date.getDayOfMonth()+" "+date.getYear();
        jlDate.setText( actualDate);
        
        Color colorMainButton = new Color(38, 69, 159); 
        jbConsumption.setBackground(colorMainButton);
        jbBeneficiaries.setBackground(colorMainButton);
        jbLunchOfTheDay.setBackground(colorMainButton);
        
        PanelWelcome pWelcome = new PanelWelcome(this);
        pWelcome.setSize(1057, 660);
        pWelcome.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pWelcome, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();      
        
        //Para poder arrastrar la ventana sin necesidad de decoracion
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                // Calcula la nueva posición de la ventana
                int newX = evt.getXOnScreen() - posX;
                int newY = evt.getYOnScreen() - posY;

                // Establece la nueva posición
                setLocation(newX, newY);
            }
        });
    }
    
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }    
    
    public JButton getButtonAddUser() {
        return jbConsumption;
    }
    
    public JButton getButtonDeleteUser() {
        return jbBeneficiaries;
    }
    
    public JButton getButtonListUsers() {
        return jbLunchOfTheDay;
    }
    
    public void setPanelContent(JPanel val) {
        content.removeAll();
        content.add(val, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }
    
    public JPanel getPanelContent() {
        return content;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jpLeftPanel = new javax.swing.JPanel();
        jlLogotipe = new javax.swing.JLabel();
        jbConsumption = new javax.swing.JButton();
        jbBeneficiaries = new javax.swing.JButton();
        jbLunchOfTheDay = new javax.swing.JButton();
        jbDownload = new javax.swing.JButton();
        jbGoOut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbWelcome = new javax.swing.JButton();
        jbUsers = new javax.swing.JButton();
        jbProducts = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jbXGouOut = new javax.swing.JButton();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1147483647, 1147483647));

        jpLeftPanel.setBackground(new java.awt.Color(38, 69, 159));

        jlLogotipe.setBackground(new java.awt.Color(102, 102, 255));
        jlLogotipe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlLogotipe.setForeground(new java.awt.Color(255, 255, 255));
        jlLogotipe.setText("Amor y Vida");
        jlLogotipe.setToolTipText("");
        jlLogotipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbConsumption.setBackground(new java.awt.Color(38, 69, 159));
        jbConsumption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbConsumption.setForeground(new java.awt.Color(255, 255, 255));
        jbConsumption.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-waiter-20.png")); // NOI18N
        jbConsumption.setText("  Registrar consumo");
        jbConsumption.setBorder(null);
        jbConsumption.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbConsumption.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbConsumption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsumptionActionPerformed(evt);
            }
        });

        jbBeneficiaries.setBackground(new java.awt.Color(38, 69, 159));
        jbBeneficiaries.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBeneficiaries.setForeground(new java.awt.Color(255, 255, 255));
        jbBeneficiaries.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-users-20.png")); // NOI18N
        jbBeneficiaries.setText("  Beneficiarios");
        jbBeneficiaries.setBorder(null);
        jbBeneficiaries.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbBeneficiaries.setHideActionText(true);
        jbBeneficiaries.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbBeneficiaries.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbBeneficiaries.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jbBeneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBeneficiariesActionPerformed(evt);
            }
        });

        jbLunchOfTheDay.setBackground(new java.awt.Color(38, 69, 159));
        jbLunchOfTheDay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbLunchOfTheDay.setForeground(new java.awt.Color(255, 255, 255));
        jbLunchOfTheDay.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-tableware-20.png")); // NOI18N
        jbLunchOfTheDay.setText("  Almuerzo del día");
        jbLunchOfTheDay.setBorder(null);
        jbLunchOfTheDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbLunchOfTheDay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbLunchOfTheDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLunchOfTheDayActionPerformed(evt);
            }
        });

        jbDownload.setBackground(new java.awt.Color(38, 69, 159));
        jbDownload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDownload.setForeground(new java.awt.Color(255, 255, 255));
        jbDownload.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-table-20.png")); // NOI18N
        jbDownload.setText("  Inventario");
        jbDownload.setBorder(null);
        jbDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbDownload.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDownloadActionPerformed(evt);
            }
        });

        jbGoOut.setBackground(new java.awt.Color(38, 69, 159));
        jbGoOut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbGoOut.setForeground(new java.awt.Color(255, 255, 255));
        jbGoOut.setText("  Salir");
        jbGoOut.setBorder(null);
        jbGoOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbGoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGoOutActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jbWelcome.setBackground(new java.awt.Color(38, 69, 159));
        jbWelcome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jbWelcome.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-home-20.png")); // NOI18N
        jbWelcome.setText("  Principal");
        jbWelcome.setBorder(null);
        jbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbWelcomeActionPerformed(evt);
            }
        });

        jbUsers.setBackground(new java.awt.Color(38, 69, 159));
        jbUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbUsers.setForeground(new java.awt.Color(255, 255, 255));
        jbUsers.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-user-20.png")); // NOI18N
        jbUsers.setText("  Usuarios");
        jbUsers.setBorder(null);
        jbUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsersActionPerformed(evt);
            }
        });

        jbProducts.setBackground(new java.awt.Color(38, 69, 159));
        jbProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbProducts.setForeground(new java.awt.Color(255, 255, 255));
        jbProducts.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-products-20.png")); // NOI18N
        jbProducts.setText("  Productos");
        jbProducts.setBorder(null);
        jbProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLeftPanelLayout = new javax.swing.GroupLayout(jpLeftPanel);
        jpLeftPanel.setLayout(jpLeftPanelLayout);
        jpLeftPanelLayout.setHorizontalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLeftPanelLayout.createSequentialGroup()
                        .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLogotipe, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbGoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jbConsumption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbBeneficiaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbLunchOfTheDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jbWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpLeftPanelLayout.setVerticalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlLogotipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLunchOfTheDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBeneficiaries, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jlDate.setBackground(new java.awt.Color(38, 69, 159));
        jlDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlDate.setText("Date");
        jlDate.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Cerrar sesión");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\AyVDiningRoom\\resources\\images\\icons8-user-45.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                contentComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jbXGouOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbXGouOut.setText("X");
        jbXGouOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbXGouOut.setBorderPainted(false);
        jbXGouOut.setContentAreaFilled(false);
        jbXGouOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbXGouOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXGouOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbXGouOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbXGouOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsumptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsumptionActionPerformed
        PanelConsumption pConsumption = new PanelConsumption(this);
        pConsumption.setSize(1057, 660);
        pConsumption.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pConsumption, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();  
    }//GEN-LAST:event_jbConsumptionActionPerformed

    private void jbBeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBeneficiariesActionPerformed
               
        ListBeneficiaries listBeneficiaries = new ListBeneficiaries(this);
        listBeneficiaries.setSize(1057, 660);
        listBeneficiaries.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(listBeneficiaries, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();    
    }//GEN-LAST:event_jbBeneficiariesActionPerformed

    private void jbLunchOfTheDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLunchOfTheDayActionPerformed
        PanelLunchOfTheDay lunchOfTheDay = new PanelLunchOfTheDay(this);
        lunchOfTheDay.setSize(1057, 660);
        lunchOfTheDay.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(lunchOfTheDay, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();                  
    }//GEN-LAST:event_jbLunchOfTheDayActionPerformed

    private void jbDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDownloadActionPerformed
                    
        PanelInventory inventory = new PanelInventory(this);
        inventory.setSize(1057, 660);
        inventory.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(inventory, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();  
    }//GEN-LAST:event_jbDownloadActionPerformed

    private void jbGoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGoOutActionPerformed
            
        //Cierra la ventana
        dispose();
        // Finaliza el programa
        System.exit(0);
    }//GEN-LAST:event_jbGoOutActionPerformed

    private void contentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_contentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_contentComponentAdded

    private void jbXGouOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXGouOutActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea cerrar la aplicación?",
                "Confirmar cierre",
                JOptionPane.YES_NO_OPTION);                                             
               
        if (confirmacion == JOptionPane.YES_OPTION) {
            //Cierra la ventana
            dispose();
            // Finaliza el programa
            System.exit(0);
        }
        
    }//GEN-LAST:event_jbXGouOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Crear un objeto JFileChooser
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);
                       
        // Verificar si el usuario seleccionó un archivo
        if (returnValue == fileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            java.io.File selectedFile = fileChooser.getSelectedFile();
            //pMenu.setFilePath(selectedFile.getAbsolutePath());
                                    
            setFilePath(selectedFile.getAbsolutePath());                        
            System.out.println("Archivo seleccionado: " + getFilePath());
            
            Color colorLabel = new Color(0, 208, 0); 
            
            //Se cambian los colores de los labels
            //setTextNameFileSelected(selectedFile.getName());
            //getNameFileSelected().setForeground(colorLabel);
            //setTextIsUploaded("ARCHIVO SUBIDO");
            //getIsUploaded().setForeground(colorLabel);
            
            //Se cambia color del icono llamando a un método para establecer el icono usando la ruta absoluta
            try {               
                setIconFromFile("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\load-64-green.png");
            } catch (MalformedURLException ex) {
                Logger.getLogger(FileManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //Se habilitan los modulos
            getButtonAddUser().setEnabled(true);
            getButtonDeleteUser().setEnabled(true);
            getButtonListUsers().setEnabled(true);                      
        } else {
            System.out.println("Operación cancelada por el usuario.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsersActionPerformed
        // TODO add your handling code here:
        ListUsers listUsers = new ListUsers(this);
        listUsers.setSize(1057, 660);
        listUsers.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(listUsers, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }//GEN-LAST:event_jbUsersActionPerformed

    private void jbWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbWelcomeActionPerformed
        // TODO add your handling code here:
        PanelWelcome pWelcome = new PanelWelcome(this);
        pWelcome.setSize(1057, 1057);
        pWelcome.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pWelcome, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();  
    }//GEN-LAST:event_jbWelcomeActionPerformed

    private void jbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductsActionPerformed
        PanelProducts pProducts = new PanelProducts(this);
        pProducts.setSize(1057, 1057);
        pProducts.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pProducts, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();  
    }//GEN-LAST:event_jbProductsActionPerformed

    public void setIconFromFile(String filePath) throws MalformedURLException {
        // Crea un ImageIcon a partir de la ruta del archivo
        ImageIcon icon = new ImageIcon(new ImageIcon(filePath).getImage());
        // Establece el icono en el JLabel
        //getIconFile().setIcon(icon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PanelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBeneficiaries;
    private javax.swing.JButton jbConsumption;
    private javax.swing.JButton jbDownload;
    private javax.swing.JButton jbGoOut;
    private javax.swing.JButton jbLunchOfTheDay;
    private javax.swing.JButton jbProducts;
    private javax.swing.JButton jbUsers;
    private javax.swing.JButton jbWelcome;
    private javax.swing.JButton jbXGouOut;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlLogotipe;
    private javax.swing.JPanel jpLeftPanel;
    // End of variables declaration//GEN-END:variables
}
