package frames;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Locale;

public class PanelMenu extends javax.swing.JFrame {   
    String actualDate;
    public String filePath;   
    private int posX, posY;
    
    public PanelMenu() {                                                                  
        setUndecorated(true);  
        initComponents();
        setLocationRelativeTo(null);                   
        
        LocalDate date = LocalDate.now();  
        
        actualDate = date.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH)+" "+date.getMonth().name()+" "+date.getDayOfMonth()+" "+date.getYear();
        jlDate.setText( actualDate);
        
        Color colorMainButton = new Color(38, 69, 159); 
        jbAddUser.setBackground(colorMainButton);
        jbDeleteUser.setBackground(colorMainButton);
        jbListUsers.setBackground(colorMainButton);
        
        FileManagement fileManagement = new FileManagement(this);
        fileManagement.setSize(1033, 654);
        fileManagement.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(fileManagement, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();      
        
        //Para poder arrastrar la ventana sin necesidad de decoracion
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                // Calcula la nueva posición de la ventana
                int newX = evt.getXOnScreen() - posX;
                int newY = evt.getYOnScreen() - posY;

                // Establece la nueva posición
                setLocation(newX, newY);
            }
        });
    }
    
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    
    public JLabel getNameFileSelected() {
        return jlNameFileSelected;
    }
    
    public void setTextNameFileSelected(String val){
        jlNameFileSelected.setText(val);
    }
    
    public JLabel getIsUploaded() {
        return jlIsUploaded;
    }
    
    public void setTextIsUploaded(String val) {
        jlIsUploaded.setText(val);
    }
    
    public JLabel getIconFile() {
        return jlIcon;
    }
    
    public void setIconFile(String val) {
        jlIcon.setText(val);
    }
    
    public JButton getButtonAddUser() {
        return jbAddUser;
    }
    
    public JButton getButtonDeleteUser() {
        return jbDeleteUser;
    }
    
    public JButton getButtonListUsers() {
        return jbListUsers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jpLeftPanel = new javax.swing.JPanel();
        jlLogotipe = new javax.swing.JLabel();
        jbAddUser = new javax.swing.JButton();
        jbDeleteUser = new javax.swing.JButton();
        jbListUsers = new javax.swing.JButton();
        jbDownload = new javax.swing.JButton();
        jbGoOut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlDate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlIsUploaded = new javax.swing.JLabel();
        jlNameFileSelected = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlIcon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jbXGouOut = new javax.swing.JButton();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1147483647, 1147483647));

        jpLeftPanel.setBackground(new java.awt.Color(38, 69, 159));

        jlLogotipe.setBackground(new java.awt.Color(102, 102, 255));
        jlLogotipe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlLogotipe.setForeground(new java.awt.Color(255, 255, 255));
        jlLogotipe.setText("Amor y Vida");
        jlLogotipe.setToolTipText("");
        jlLogotipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbAddUser.setBackground(new java.awt.Color(38, 69, 159));
        jbAddUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAddUser.setForeground(new java.awt.Color(255, 255, 255));
        jbAddUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\icons8-add-user-20.png")); // NOI18N
        jbAddUser.setText("  Ingresar usuarios");
        jbAddUser.setBorder(null);
        jbAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbAddUser.setEnabled(false);
        jbAddUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddUserActionPerformed(evt);
            }
        });

        jbDeleteUser.setBackground(new java.awt.Color(38, 69, 159));
        jbDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        jbDeleteUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\icons8-denied-20.png")); // NOI18N
        jbDeleteUser.setText("  Eliminar usuarios");
        jbDeleteUser.setBorder(null);
        jbDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbDeleteUser.setEnabled(false);
        jbDeleteUser.setHideActionText(true);
        jbDeleteUser.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbDeleteUser.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jbDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteUserActionPerformed(evt);
            }
        });

        jbListUsers.setBackground(new java.awt.Color(38, 69, 159));
        jbListUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbListUsers.setForeground(new java.awt.Color(255, 255, 255));
        jbListUsers.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\icons8-list-20.png")); // NOI18N
        jbListUsers.setText("  Lista de usuarios");
        jbListUsers.setBorder(null);
        jbListUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbListUsers.setEnabled(false);
        jbListUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListUsersActionPerformed(evt);
            }
        });

        jbDownload.setBackground(new java.awt.Color(38, 69, 159));
        jbDownload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDownload.setForeground(new java.awt.Color(255, 255, 255));
        jbDownload.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\icons8-export-20.png")); // NOI18N
        jbDownload.setText("  Gestión de archivos");
        jbDownload.setBorder(null);
        jbDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbDownload.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDownloadActionPerformed(evt);
            }
        });

        jbGoOut.setBackground(new java.awt.Color(38, 69, 159));
        jbGoOut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jbGoOut.setForeground(new java.awt.Color(255, 255, 255));
        jbGoOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\icons8-off-20.png")); // NOI18N
        jbGoOut.setText("  Salir");
        jbGoOut.setBorder(null);
        jbGoOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbGoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGoOutActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpLeftPanelLayout = new javax.swing.GroupLayout(jpLeftPanel);
        jpLeftPanel.setLayout(jpLeftPanelLayout);
        jpLeftPanelLayout.setHorizontalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLeftPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jbAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpLeftPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogotipe, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLeftPanelLayout.setVerticalGroup(
            jpLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlLogotipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlDate.setBackground(new java.awt.Color(38, 69, 159));
        jlDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlDate.setText("Date");
        jlDate.setToolTipText("");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jlIsUploaded.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlIsUploaded.setForeground(new java.awt.Color(255, 51, 51));
        jlIsUploaded.setText("CARGAR ARCHIVO");

        jlNameFileSelected.setBackground(new java.awt.Color(255, 255, 255));
        jlNameFileSelected.setForeground(new java.awt.Color(255, 51, 51));
        jlNameFileSelected.setText("Ningun archivo subido");
        jlNameFileSelected.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\judav\\Desktop\\Desktop\\All\\React js\\Java\\register_beneficiaries\\RegisterBeneficiaries\\register_beneficiaries\\resources\\images\\load-64-red.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlIcon)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNameFileSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIsUploaded, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlNameFileSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlIsUploaded, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(153, 153, 153));
        content.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                contentComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        jbXGouOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbXGouOut.setText("X");
        jbXGouOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbXGouOut.setBorderPainted(false);
        jbXGouOut.setContentAreaFilled(false);
        jbXGouOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbXGouOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXGouOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbXGouOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbXGouOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddUserActionPerformed
                      
        
        PanelAddUser pAddUser = new PanelAddUser(this);
        pAddUser.setSize(998, 598);
        pAddUser.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pAddUser, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();                                                 
    }//GEN-LAST:event_jbAddUserActionPerformed

    private void jbDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteUserActionPerformed
        
        
        PanelDeleteUser pDelUser = new PanelDeleteUser();
        pDelUser.setSize(998, 598);
        pDelUser.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(pDelUser, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();    
    }//GEN-LAST:event_jbDeleteUserActionPerformed

    private void jbListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListUsersActionPerformed
        
        
        ListUsers listUsers = new ListUsers(this);
        listUsers.setSize(1033, 654);
        listUsers.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(listUsers, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }//GEN-LAST:event_jbListUsersActionPerformed

    private void jbDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDownloadActionPerformed
               
        
        FileManagement fileManagement = new FileManagement(this);
        fileManagement.setSize(1033, 654);
        fileManagement.setLocation(0, 0);                  
        
        content.removeAll();
        content.add(fileManagement, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();  
    }//GEN-LAST:event_jbDownloadActionPerformed

    private void jbGoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGoOutActionPerformed
            
        //Cierra la ventana
        dispose();
        // Finaliza el programa
        System.exit(0);
    }//GEN-LAST:event_jbGoOutActionPerformed

    private void contentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_contentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_contentComponentAdded

    private void jbXGouOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXGouOutActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea cerrar la aplicación?",
                "Confirmar cierre",
                JOptionPane.YES_NO_OPTION);                                             
               
        if (confirmacion == JOptionPane.YES_OPTION) {
            //Cierra la ventana
            dispose();
            // Finaliza el programa
            System.exit(0);
        }
        
    }//GEN-LAST:event_jbXGouOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PanelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbAddUser;
    private javax.swing.JButton jbDeleteUser;
    private javax.swing.JButton jbDownload;
    private javax.swing.JButton jbGoOut;
    private javax.swing.JButton jbListUsers;
    private javax.swing.JButton jbXGouOut;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlIsUploaded;
    private javax.swing.JLabel jlLogotipe;
    private javax.swing.JLabel jlNameFileSelected;
    private javax.swing.JPanel jpLeftPanel;
    // End of variables declaration//GEN-END:variables
}
